
-- MEMBER        회원	      MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL_CHECK, MEMBER_RDATE, MEMBER_CHECK 
-- BLACKLIST     블랙리스트      BLACKLIST_NUM, MEMBER_ID, BLACKLIST_STOP, BLACKLIST_DATE, BLACKLIST_CNT
-- ADDRESS       배송지관리       ADDR_NUM, MEMBER_ID, ADDR_NAME, ADDR_RECIVER, ADDR_PHONE, ADDR_POST, ADDR_ROADNAME, ADDR_DETAIL
-- CATEGORY      카테고리        CATEGORY_NUM, CATEGORY_SUB
-- CREATOR       크리에이터       CREATOR_NUM, CREATOR_TYPE, CREATOR_PHONE, CREATOR_CHECK, CREATOR_NAME
-- PROJECT       프로젝트        PROJECT_NUM, CREATOR_NUM, CATEGORY_NUM, PROJECT_SUB, PROJECT_GOAL, PROJECT_COMMENT, PROJECT_DETAIL, PROJECT_PRICE, PROJECT_OPEN, PROJECT_CLOSE, PROJECT_DATE, PROJECT_MDATE, PROJECT_LEVEL
-- REWARD        리워드         REWARD_NUM, PROJECT_NUM, REWARD_SUB, REWARD_PRICE, REWARD_CNT, REWARD_DATE
-- ORDER         주문	      ORDER_NUM, ADDR_NUM, REWARD_NUM, MEMBER_ID, ORDER_NAME, ORDER_PRICE, ORDER_DATE, ORDER_STATEMENT, ORDER_OPTION, ORDER_DELIVERY
-- PAYMENT       결제           PAYMENT_NUM, ADDR_NUM, ORDER_NUM, MEMBER_ID, PAYMENT_PAY, PAYMENT_PRICE, PAYMENT_DATE, PAYMENT_TIME
-- COMMUNITY     커뮤니티        COMMUNITY_NUM, MEMBER_ID, COMMUNITY_SUB, COMMUNITY_CON, COMMUNITY_DATE, COMMUNITY_MDATE, COMMUNITY_VIEW
-- COMMUNITY_REPLY  커뮤니티댓글   COM_RE_NUM, MEMBER_ID, COMMUNITY_NUM, COM_RE_CON, COM_RE_DATE, COM_RE_MDATE
-- REPORT        신고           REPORT_NUM, COM_RE_NUM, REPORT_REASON, REPORT_DATE, REPORT_CHECK
-- QNA           질문게시판       QNA_NUM, QNA_SUB, QNA_CON, QNA_DATE, QNA_VIEW, QNA_CHECK
-- QNA_REPLY     질문게시판댓글    QNA_NUM, QNA_RE_NUM, QNA_RE_CON, QNA_RE_DATE, QNA_RE_NAME
-- NOTICE        공지사항        NOTICE_NUM, NOTICE_SUB, NOTICE_CON, NOTICE_DATE, NOTICE_VIEW

/* 테이블 */
drop table NOTICE; 
drop table QNA_REPLY;
drop table QNA;
/* drop table REPORT; */
drop table COMMUNITY_REPLY; 
drop table COMMUNITY; 
/* drop table PAYMENT; */
drop table MEM_ORDER; 
drop table REWARD; 
drop table PROJECT;
drop table CREATOR;
drop table CATEGORY; 
drop table ADDRESS;  
/* drop table BLACKLIST; */
drop table MEMBER;


/* 시퀀스 */
drop sequence SEQ_NOTICE_NUM;
drop sequence SEQ_QNA_RE_NUM;
drop sequence SEQ_QNA_NUM;
drop sequence SEQ_COM_RE_NUM;
drop sequence SEQ_COMMUNITY_NUM;
drop sequence SEQ_MORDER_NUM;
drop sequence SEQ_REWARD_NUM;
drop sequence SEQ_PROJ_NUM;
drop sequence SEQ_CREATOR_NUM;
drop sequence SEQ_CATEGORY_NUM;
drop sequence SEQ_ADDR_NUM;


purge recyclebin;
select TNAME from TAB;